version: "3"
services:
  node:
    build:
      dockerfile: src/Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
      - PORT=${PORT}
      - BOT_SERVER_URL=${BOT_SERVER_URL}
      - SSL_CERT_BASE64=${SSL_CERT_BASE64}
      - SSL_KEY_BASE64=${SSL_KEY_BASE64}
    ports:
      - "${PORT}:${PORT}"
    restart: always
